import { Geist, Geist_Mono } from "next/font/google";
import '/app/globals.css';
import { Suspense } from "react"; // <-- import Suspense

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Authentication",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable}`}>
      <Suspense fallback={<div>Loading...</div>}>
        {children}
      </Suspense>
    </div>
  );
}
